name: FlashlightPlus
author: FallenYouth
authors:
    - sarhatabaot
version: ${project.version}
main: com.hybrah.flashlightplus.FlashlightPlus
description: Explore the darkcaves in minecraft without a torch!

commands:
    flashlight:
        usage: /<command>
        description: "Toggles Flashlight"
        aliases: [flash, fl, flashl, light, torch]
        permission: flashlight.use
        permission-message: You do not have <permission>.
    
permissions:
    flashlight.use:
        description: Use the flashlight on command.
        default: op